import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  BookOpen, 
  Users, 
  Eye, 
  Download, 
  Printer, 
  TrendingUp, 
  Award, 
  Layers,
  BarChart2,
  Activity
} from 'lucide-react';
import api from '@/services/api';
import DashboardHeader from '@/components/ui/DashboardHeader';
import Button from '@/components/ui/Button';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { toast } from 'sonner';
import { useSmartPolling } from '@/hooks/useSmartPolling';
import { ChartSkeleton } from '@/components/ui/Skeleton';

interface AnalyticsData {
  journals: number;
  articles: number;
  drafts: number;
  authors: number;
  users: number;
  trends: {
    journals: { trend: string; isPositive: boolean };
    articles: { trend: string; isPositive: boolean };
    authors: { trend: string; isPositive: boolean };
    users: { trend: string; isPositive: boolean };
  };
  websiteChartData: { date: string; views: number; downloads: number }[];
  chartData: { date: string; publications?: number; users?: number; trash?: number; system?: number; actions: number }[];
}

interface TopArticle {
  id: number;
  title: string;
  journal: string;
  views: number;
  published_date: string;
}

interface TopAuthor {
  name: string;
  papers: number;
  department: string;
}

const Analytics: React.FC = () => {
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);

  // Sample/derived leaderboard data for repository insights
  const [topArticles, setTopArticles] = useState<TopArticle[]>([]);
  const [topAuthors, setTopAuthors] = useState<TopAuthor[]>([]);
  const [categoryBreakdown, setCategoryBreakdown] = useState<{ name: string; count: number; percentage: number }[]>([]);

  const fetchAnalytics = async (isBackground = false) => {
    try {
      if (!isBackground) setLoading(true);
      const res = await api.get('/dashboard/stats');
      const stats = res.data;
      setData(stats);

      if (stats.categoryBreakdown) {
        setCategoryBreakdown(stats.categoryBreakdown);
      }

      if (stats.topArticles) {
        setTopArticles(stats.topArticles);
      }

      if (stats.topAuthors) {
        setTopAuthors(stats.topAuthors);
      }
    } catch (err) {
      console.error('Failed to fetch analytics', err);
    } finally {
      if (!isBackground) setLoading(false);
    }
  };

  // 120-Second (2 Minute) Smart Background Polling for Analytics
  useSmartPolling(() => fetchAnalytics(true), 120000);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const userObj = JSON.parse(localStorage.getItem('user') || '{}');
  const userName = userObj.name ? `${userObj.name} (${userObj.role || 'Super Admin'})` : 'IT Super Admin';
  const now = new Date();
  const currentDate = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const currentTime = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });

  const topAuthorStr = topAuthors.length > 0 ? `${topAuthors[0].name} (${topAuthors[0].papers} publications)` : 'None';
  const topArticleStr = topArticles.length > 0 ? `${topArticles[0].title} (${topArticles[0].views} views)` : 'None';

  const handleExportCSV = () => {
    if (!data) return;

    const csvRows = [
      ['Metric', 'Value'],
      ['Date', `"${currentDate}"`],
      ['Time', `"${currentTime}"`],
      ['Generated by which user', `"${userName}"`],
      ['Total Published Articles', data.articles || 0],
      ['Total Journals', data.journals || 0],
      ['Total Authors', data.authors || 0],
      ['Registered Admin Users', data.users || 0],
      ['Drafts', data.drafts || 0],
      ['Top Contributor (Author)', `"${topAuthorStr}"`],
      ['Top Readership Article', `"${topArticleStr}"`],
    ];

    const csvContent = csvRows.map(e => e.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `repository_analytics_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success('CSV Report exported successfully!');
  };

  const handlePrint = () => {
    window.print();
  };

  const totalViews = data?.websiteChartData?.reduce((acc: number, curr: any) => acc + (curr.views || 0), 0) || 0;
  const totalDownloads = data?.websiteChartData?.reduce((acc: number, curr: any) => acc + (curr.downloads || 0), 0) || 0;
  const totalActions = data?.chartData?.reduce((acc: number, curr: any) => acc + (curr.actions || 0), 0) || 0;
  const totalPublications = data?.chartData?.reduce((acc: number, curr: any) => acc + (curr.publications || 0), 0) || 0;
  const totalUserActions = data?.chartData?.reduce((acc: number, curr: any) => acc + (curr.users || 0), 0) || 0;
  const totalTrashActions = data?.chartData?.reduce((acc: number, curr: any) => acc + (curr.trash || 0), 0) || 0;
  const totalSystemActions = data?.chartData?.reduce((acc: number, curr: any) => acc + (curr.system || 0), 0) || 0;

  return (
    <div className="space-y-4 sm:space-y-8 font-sans w-full print:p-0">
      <DashboardHeader 
        title="Reports & Analytics"
        helpText="Detailed traffic analytics, article read counts, PDF downloads, and readership demographic statistics."
      >
        <div className="flex items-center gap-1.5 sm:gap-2 print:hidden">
          <Button 
            onClick={handleExportCSV} 
            variant="outline" 
            className="flex items-center gap-1.5 text-[11px] sm:text-xs h-8 sm:h-9 px-2.5 sm:px-3 cursor-pointer shrink-0"
            title="Export CSV"
          >
            <Download className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Export CSV</span>
          </Button>
          <Button 
            onClick={handlePrint} 
            className="flex items-center gap-1.5 text-[11px] sm:text-xs h-8 sm:h-9 px-2.5 sm:px-3 cursor-pointer shrink-0"
            title="Print Summary"
          >
            <Printer className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Print Summary</span>
          </Button>
        </div>
      </DashboardHeader>

      {/* Executive Report Header - Printed Only */}
      <div className="hidden print:block border border-slate-300 p-5 mb-6 space-y-3 bg-slate-50 text-[12px] font-sans">
        <div className="flex items-center justify-between border-b border-slate-300 pb-2">
          <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wider">
            Executive System Summary & Analytics Report
          </h2>
          <span className="text-[10px] font-mono text-slate-500">Official Repository Record</span>
        </div>
        <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-slate-700">
          <div><span className="font-semibold text-slate-900">Date:</span> {currentDate}</div>
          <div><span className="font-semibold text-slate-900">Time:</span> {currentTime}</div>
          <div className="col-span-2"><span className="font-semibold text-slate-900">Generated by user:</span> {userName}</div>
          <div><span className="font-semibold text-slate-900">Total Published Articles:</span> {data?.articles || 0}</div>
          <div><span className="font-semibold text-slate-900">Total Journals:</span> {data?.journals || 0}</div>
          <div><span className="font-semibold text-slate-900">Total Authors:</span> {data?.authors || 0}</div>
          <div><span className="font-semibold text-slate-900">Registered Admin Users:</span> {data?.users || 0}</div>
          <div><span className="font-semibold text-slate-900">Drafts:</span> {data?.drafts || 0}</div>
          <div><span className="font-semibold text-slate-900">30-Day Article Views:</span> {totalViews.toLocaleString()}</div>
          <div><span className="font-semibold text-slate-900">30-Day PDF Reads:</span> {totalDownloads.toLocaleString()}</div>
          <div className="col-span-2"><span className="font-semibold text-slate-900">Top Contributor (Author):</span> {topAuthorStr}</div>
          <div className="col-span-2"><span className="font-semibold text-slate-900">Top Readership Article:</span> {topArticleStr}</div>
        </div>
      </div>

      {/* Quick Stats Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-2.5 sm:gap-6">
        {/* Total Articles */}
        <div className="border border-border bg-surface p-3.5 sm:p-6 space-y-2 sm:space-y-4">
          <div className="flex justify-between items-start">
            <span className="text-[10px] sm:text-[11px] font-bold text-muted uppercase tracking-wider truncate">Total Articles</span>
            <div className="p-1.5 sm:p-2.5 bg-emerald-500/10 text-emerald-600 shrink-0">
              <FileText className="h-3.5 sm:h-4 w-3.5 sm:w-4" />
            </div>
          </div>
          <div className="space-y-0.5 sm:space-y-1">
            <div className="text-xl sm:text-2xl font-bold text-primary font-mono flex items-center min-h-[28px] sm:min-h-[32px]">
              {loading ? (
                <span className="w-4 h-4 border-2 border-primary/20 border-t-primary rounded-full animate-spin inline-block" />
              ) : (
                data?.articles || 0
              )}
            </div>
            <div className="flex items-center gap-1 text-[10px] sm:text-[11px] font-medium text-emerald-600 truncate">
              <TrendingUp className="h-3 w-3 shrink-0" />
              <span>{data?.trends?.articles?.trend || 'Stable'}</span>
            </div>
          </div>
        </div>

        {/* Active Journals */}
        <div className="border border-border bg-surface p-3.5 sm:p-6 space-y-2 sm:space-y-4">
          <div className="flex justify-between items-start">
            <span className="text-[10px] sm:text-[11px] font-bold text-muted uppercase tracking-wider truncate">Active Journals</span>
            <div className="p-1.5 sm:p-2.5 bg-blue-500/10 text-blue-600 shrink-0">
              <BookOpen className="h-3.5 sm:h-4 w-3.5 sm:w-4" />
            </div>
          </div>
          <div className="space-y-0.5 sm:space-y-1">
            <div className="text-xl sm:text-2xl font-bold text-primary font-mono flex items-center min-h-[28px] sm:min-h-[32px]">
              {loading ? (
                <span className="w-4 h-4 border-2 border-primary/20 border-t-primary rounded-full animate-spin inline-block" />
              ) : (
                data?.journals || 0
              )}
            </div>
            <div className="flex items-center gap-1 text-[10px] sm:text-[11px] font-medium text-blue-600 truncate">
              <TrendingUp className="h-3 w-3 shrink-0" />
              <span>{data?.trends?.journals?.trend || 'Stable'}</span>
            </div>
          </div>
        </div>

        {/* Authors */}
        <div className="border border-border bg-surface p-3.5 sm:p-6 space-y-2 sm:space-y-4">
          <div className="flex justify-between items-start">
            <span className="text-[10px] sm:text-[11px] font-bold text-muted uppercase tracking-wider truncate">Total Authors</span>
            <div className="p-1.5 sm:p-2.5 bg-purple-500/10 text-purple-600 shrink-0">
              <Users className="h-3.5 sm:h-4 w-3.5 sm:w-4" />
            </div>
          </div>
          <div className="space-y-0.5 sm:space-y-1">
            <div className="text-xl sm:text-2xl font-bold text-primary font-mono flex items-center min-h-[28px] sm:min-h-[32px]">
              {loading ? (
                <span className="w-4 h-4 border-2 border-primary/20 border-t-primary rounded-full animate-spin inline-block" />
              ) : (
                data?.authors || 0
              )}
            </div>
            <div className="flex items-center gap-1 text-[10px] sm:text-[11px] font-medium text-purple-600 truncate">
              <TrendingUp className="h-3 w-3 shrink-0" />
              <span>{data?.trends?.authors?.trend || 'Stable'}</span>
            </div>
          </div>
        </div>

        {/* Reader Views */}
        <div className="border border-border bg-surface p-3.5 sm:p-6 space-y-2 sm:space-y-4">
          <div className="flex justify-between items-start">
            <span className="text-[10px] sm:text-[11px] font-bold text-muted uppercase tracking-wider truncate">Reader Views</span>
            <div className="p-1.5 sm:p-2.5 bg-amber-500/10 text-amber-600 shrink-0">
              <Eye className="h-3.5 sm:h-4 w-3.5 sm:w-4" />
            </div>
          </div>
          <div className="space-y-0.5 sm:space-y-1">
            <div className="text-xl sm:text-2xl font-bold text-primary font-mono flex items-center min-h-[28px] sm:min-h-[32px]">
              {loading ? (
                <span className="w-4 h-4 border-2 border-primary/20 border-t-primary rounded-full animate-spin inline-block" />
              ) : (
                totalViews.toLocaleString()
              )}
            </div>
            <div className="flex items-center gap-1 text-[10px] sm:text-[11px] font-medium text-muted truncate">
              <span>30-day engagement</span>
            </div>
          </div>
        </div>
      </div>

      {/* Row 1: Readership Traffic & Category Distribution */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
        {/* Readership & Activity Trend (2 cols) */}
        <div className="lg:col-span-2">
          {loading ? (
            <ChartSkeleton />
          ) : (
            <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 h-full">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-border pb-3 gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <TrendingUp className="h-4 w-4 text-primary/70 shrink-0" />
                  <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider truncate">
                    Readership & Traffic Trend (30 Days)
                  </h2>
                </div>
                {/* Right-aligned legend */}
                <div className="flex items-center gap-4 text-[10px] sm:text-[11px] font-mono">
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-[#002d72] shrink-0" />
                    <span className="text-foreground font-medium">Views</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-[#059669] shrink-0" />
                    <span className="text-foreground font-medium">PDF Reads</span>
                  </div>
                </div>
              </div>

              <div className="h-48 sm:h-64 w-full pt-1">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={data?.websiteChartData && data.websiteChartData.length > 0 ? data.websiteChartData : [
                    { date: 'Jul 05', views: 0, downloads: 0 }, { date: 'Jul 10', views: 0, downloads: 0 }, { date: 'Jul 15', views: 0, downloads: 0 },
                    { date: 'Jul 20', views: 0, downloads: 0 }, { date: 'Jul 25', views: 0, downloads: 0 }, { date: 'Aug 01', views: 0, downloads: 0 }
                  ]}>
                    <defs>
                      <linearGradient id="colorReportViews" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#002d72" stopOpacity={0.25}/>
                        <stop offset="95%" stopColor="#002d72" stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorReportDownloads" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#059669" stopOpacity={0.25}/>
                        <stop offset="95%" stopColor="#059669" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(0,0,0,0.06)" />
                    <XAxis dataKey="date" tickLine={false} axisLine={false} tick={{ fontSize: 9, fill: '#64748b' }} dy={5} />
                    <YAxis tickLine={false} axisLine={false} tick={{ fontSize: 9, fill: '#64748b' }} />
                    <Tooltip 
                      content={({ active, payload, label }) => {
                        if (active && payload && payload.length) {
                          return (
                            <div className="bg-surface border border-border p-2.5 shadow-md text-xs font-sans space-y-1.5 min-w-[150px]">
                              <div className="border-b border-border/80 pb-1 font-mono font-semibold text-foreground">
                                {label}
                              </div>
                              <div className="space-y-1 text-[11px]">
                                {payload.map((entry: any, index: number) => (
                                  <div key={`item-${index}`} className="flex items-center justify-between gap-3">
                                    <div className="flex items-center gap-1.5">
                                      <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: entry.color }} />
                                      <span className="text-muted">{entry.name}</span>
                                    </div>
                                    <span className="font-mono font-semibold text-foreground">{entry.value}</span>
                                  </div>
                                ))}
                              </div>
                            </div>
                          );
                        }
                        return null;
                      }}
                    />
                    <Area type="monotone" dataKey="views" stroke="#002d72" strokeWidth={2} fillOpacity={1} fill="url(#colorReportViews)" name="Article Views" />
                    <Area type="monotone" dataKey="downloads" stroke="#059669" strokeWidth={2} fillOpacity={1} fill="url(#colorReportDownloads)" name="PDF Reads" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}
        </div>

        {/* Content Category Distribution (1 col) */}
        <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 flex flex-col justify-between">
          <div className="flex items-center justify-between border-b border-border pb-3">
            <div className="flex items-center gap-2">
              <Layers className="h-4 w-4 text-primary/70" />
              <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider">Category Distribution</h2>
            </div>
          </div>

          <div className="space-y-3 pt-1 max-h-[250px] overflow-y-auto custom-scrollbar pr-1 print:max-h-none print:overflow-visible">
            {categoryBreakdown.length === 0 ? (
              <p className="text-xs text-muted py-8 text-center">No categories recorded yet.</p>
            ) : (
              categoryBreakdown.map((cat: any) => (
                <div key={cat.name} className="space-y-1">
                  <div className="flex justify-between items-center text-[11px] sm:text-[12px]">
                    <span className="font-medium text-primary truncate max-w-[150px] sm:max-w-[190px]">{cat.name}</span>
                    <span className="font-mono text-muted text-[10px] sm:text-[11px]">{cat.count} ({cat.percentage}%)</span>
                  </div>
                  <div className="w-full bg-background border border-border h-2 overflow-hidden p-0.5">
                    <div 
                      className="bg-primary h-full transition-all duration-500 ease-out" 
                      style={{ width: `${cat.percentage}%` }}
                    />
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>

      {/* Row 2: Portal Activity (Stacked Bar Chart) & 30-Day Activity Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6">
        {/* Portal Activity (2 cols) */}
        <div className="lg:col-span-2">
          {loading ? (
            <ChartSkeleton />
          ) : (
            <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 h-full">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-border pb-3 gap-2">
                <div className="flex items-center gap-2 min-w-0">
                  <BarChart2 className="h-4 w-4 text-primary/70 shrink-0" />
                  <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider truncate">
                    Portal & Administrative Activity (30 Days)
                  </h2>
                </div>
                {/* Multi-category Stacked Legend */}
                <div className="flex flex-wrap items-center gap-3 text-[10px] sm:text-[11px] font-mono">
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 bg-[#002d72] shrink-0" />
                    <span className="text-foreground font-medium">Content</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 bg-[#d97706] shrink-0" />
                    <span className="text-foreground font-medium">Users</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 bg-[#059669] shrink-0" />
                    <span className="text-foreground font-medium">Trash/Restores</span>
                  </div>
                  <div className="flex items-center gap-1.5">
                    <span className="w-2 h-2 bg-[#64748b] shrink-0" />
                    <span className="text-foreground font-medium">System</span>
                  </div>
                </div>
              </div>

              <div className="h-48 sm:h-64 w-full pt-1">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={data?.chartData || []} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="rgba(0,0,0,0.06)" />
                    <XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fontSize: 9, fill: '#64748b' }} dy={10} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 9, fill: '#64748b' }} />
                    <Tooltip 
                      cursor={{ fill: 'rgba(0,0,0,0.03)' }}
                      content={({ active, payload, label }) => {
                        if (active && payload && payload.length) {
                          const total = payload.reduce((acc: number, cur: any) => acc + (cur.value || 0), 0);
                          return (
                            <div className="bg-surface border border-border p-2.5 shadow-md text-xs font-sans space-y-2 min-w-[200px]">
                              <div className="flex items-center justify-between border-b border-border/80 pb-1.5 gap-4 font-mono">
                                <span className="font-semibold text-foreground">{label}</span>
                                <span className="font-bold text-[11px] text-primary bg-primary/10 px-1.5 py-0.5">
                                  {total} Total
                                </span>
                              </div>
                              <div className="space-y-1 text-[11px]">
                                {payload.map((entry: any, index: number) => (
                                  entry.value > 0 ? (
                                    <div key={`item-${index}`} className="flex items-center justify-between gap-3">
                                      <div className="flex items-center gap-1.5">
                                        <span className="w-1.5 h-1.5 shrink-0" style={{ backgroundColor: entry.color }} />
                                        <span className="text-muted">{entry.name}</span>
                                      </div>
                                      <span className="font-mono font-semibold text-foreground">{entry.value}</span>
                                    </div>
                                  ) : null
                                ))}
                              </div>
                            </div>
                          );
                        }
                        return null;
                      }}
                    />
                    <Bar dataKey="publications" stackId="a" fill="#002d72" name="Content & Articles" />
                    <Bar dataKey="users" stackId="a" fill="#d97706" name="User Management" />
                    <Bar dataKey="trash" stackId="a" fill="#059669" name="Trash & Restores" />
                    <Bar dataKey="system" stackId="a" fill="#64748b" radius={[2, 2, 0, 0]} name="System & Config" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>
          )}
        </div>

        {/* 30-Day Activity Summary Breakdown (1 col) */}
        <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 flex flex-col justify-between">
          <div className="flex items-center justify-between border-b border-border pb-3">
            <div className="flex items-center gap-2">
              <Activity className="h-4 w-4 text-primary/70" />
              <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider">
                30-Day Operations
              </h2>
            </div>
            <span className="text-[10px] font-mono font-bold text-primary bg-primary/10 px-2 py-0.5">
              {totalActions.toLocaleString()} Operations
            </span>
          </div>

          <div className="space-y-3.5 pt-1">
            {/* Content & Articles */}
            <div className="space-y-1">
              <div className="flex justify-between items-center text-[11px] sm:text-[12px]">
                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 bg-[#002d72] shrink-0" />
                  <span className="font-medium text-foreground">Content & Publications</span>
                </div>
                <span className="font-mono font-bold text-primary text-[11px]">
                  {totalPublications.toLocaleString()} ({totalActions > 0 ? Math.round((totalPublications / totalActions) * 100) : 0}%)
                </span>
              </div>
              <div className="w-full bg-background border border-border h-2 overflow-hidden p-0.5">
                <div 
                  className="bg-[#002d72] h-full transition-all duration-500" 
                  style={{ width: `${totalActions > 0 ? (totalPublications / totalActions) * 100 : 0}%` }}
                />
              </div>
            </div>

            {/* User Governance */}
            <div className="space-y-1">
              <div className="flex justify-between items-center text-[11px] sm:text-[12px]">
                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 bg-[#d97706] shrink-0" />
                  <span className="font-medium text-foreground">User Management</span>
                </div>
                <span className="font-mono font-bold text-primary text-[11px]">
                  {totalUserActions.toLocaleString()} ({totalActions > 0 ? Math.round((totalUserActions / totalActions) * 100) : 0}%)
                </span>
              </div>
              <div className="w-full bg-background border border-border h-2 overflow-hidden p-0.5">
                <div 
                  className="bg-[#d97706] h-full transition-all duration-500" 
                  style={{ width: `${totalActions > 0 ? (totalUserActions / totalActions) * 100 : 0}%` }}
                />
              </div>
            </div>

            {/* Trash & Restores */}
            <div className="space-y-1">
              <div className="flex justify-between items-center text-[11px] sm:text-[12px]">
                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 bg-[#059669] shrink-0" />
                  <span className="font-medium text-foreground">Trash & Restorations</span>
                </div>
                <span className="font-mono font-bold text-primary text-[11px]">
                  {totalTrashActions.toLocaleString()} ({totalActions > 0 ? Math.round((totalTrashActions / totalActions) * 100) : 0}%)
                </span>
              </div>
              <div className="w-full bg-background border border-border h-2 overflow-hidden p-0.5">
                <div 
                  className="bg-[#059669] h-full transition-all duration-500" 
                  style={{ width: `${totalActions > 0 ? (totalTrashActions / totalActions) * 100 : 0}%` }}
                />
              </div>
            </div>

            {/* System & Governance */}
            <div className="space-y-1">
              <div className="flex justify-between items-center text-[11px] sm:text-[12px]">
                <div className="flex items-center gap-1.5">
                  <span className="w-2 h-2 bg-[#64748b] shrink-0" />
                  <span className="font-medium text-foreground">System & Governance</span>
                </div>
                <span className="font-mono font-bold text-primary text-[11px]">
                  {totalSystemActions.toLocaleString()} ({totalActions > 0 ? Math.round((totalSystemActions / totalActions) * 100) : 0}%)
                </span>
              </div>
              <div className="w-full bg-background border border-border h-2 overflow-hidden p-0.5">
                <div 
                  className="bg-[#64748b] h-full transition-all duration-500" 
                  style={{ width: `${totalActions > 0 ? (totalSystemActions / totalActions) * 100 : 0}%` }}
                />
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Row 2: Leaderboards & Full Rankings */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6">
        {/* Research Paper Readership Ranking */}
        <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 flex flex-col print:border-none print:p-0">
          <div className="flex items-center justify-between border-b border-border pb-3">
            <div className="flex items-center gap-2">
              <Award className="h-4 w-4 text-amber-600" />
              <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider">Paper Readership Ranking</h2>
            </div>
            <span className="text-[9px] sm:text-[10px] font-mono text-muted uppercase">By Views</span>
          </div>

          <div className="divide-y divide-border border border-border max-h-[340px] overflow-y-auto custom-scrollbar pr-1 print:max-h-none print:overflow-visible">
            {topArticles.length === 0 ? (
              <p className="text-xs text-muted py-8 text-center">No articles available.</p>
            ) : (
              topArticles.map((art: TopArticle, index: number) => (
                <div key={art.id} className="p-2.5 sm:p-3 text-[11px] sm:text-[12px] flex items-center justify-between gap-3 hover:bg-background/50 transition-colors">
                  <div className="flex items-center gap-2.5 min-w-0">
                    <span className={`w-4 h-4 sm:w-5 sm:h-5 shrink-0 rounded-full flex items-center justify-center text-[9px] sm:text-[10px] font-bold font-mono ${
                      index === 0 ? 'bg-amber-500 text-white' : index === 1 ? 'bg-slate-400 text-white' : index === 2 ? 'bg-amber-700 text-white' : 'bg-muted/20 text-muted'
                    }`}>
                      {index + 1}
                    </span>
                    <div className="min-w-0">
                      <p className="font-medium text-primary truncate" title={art.title}>{art.title}</p>
                      <p className="text-[9px] sm:text-[10px] text-muted truncate">{art.journal} • {art.published_date}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-1 shrink-0 text-[10px] sm:text-xs font-mono font-bold text-primary bg-background border border-border px-1.5 sm:px-2 py-0.5">
                    <Eye className="h-3 w-3 text-muted" />
                    <span>{art.views.toLocaleString()}</span>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Author Contribution Ranking */}
        <div className="border border-border bg-surface p-4 sm:p-6 space-y-3.5 sm:space-y-5 flex flex-col print:border-none print:p-0">
          <div className="flex items-center justify-between border-b border-border pb-3">
            <div className="flex items-center gap-2">
              <Users className="h-4 w-4 text-primary/50" />
              <h2 className="text-[11px] sm:text-[12px] font-semibold text-primary uppercase tracking-wider">Author Contribution Ranking</h2>
            </div>
            <span className="text-[9px] sm:text-[10px] font-mono text-muted uppercase">By Papers</span>
          </div>

          <div className="divide-y divide-border border border-border max-h-[340px] overflow-y-auto custom-scrollbar pr-1 print:max-h-none print:overflow-visible">
            {topAuthors.length === 0 ? (
              <p className="text-xs text-muted py-8 text-center">No author contributions recorded.</p>
            ) : (
              topAuthors.map((author: TopAuthor, index: number) => (
                <div key={author.name} className="p-2.5 sm:p-3 text-[11px] sm:text-[12px] flex items-center justify-between gap-3 hover:bg-background/50 transition-colors">
                  <div className="flex items-center gap-2.5 min-w-0">
                    <span className="w-4 h-4 sm:w-5 sm:h-5 shrink-0 bg-primary/10 text-primary rounded-full flex items-center justify-center text-[9px] sm:text-[10px] font-bold font-mono">
                      {index + 1}
                    </span>
                    <div className="min-w-0">
                      <p className="font-medium text-primary truncate">{author.name}</p>
                      <p className="text-[9px] sm:text-[10px] text-muted truncate">{author.department}</p>
                    </div>
                  </div>
                  <div className="shrink-0 text-[10px] sm:text-xs font-mono font-bold text-primary bg-background border border-border px-1.5 sm:px-2 py-0.5">
                    {author.papers} pub{author.papers !== 1 ? 's' : ''}
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Analytics;
